### ISSUE TITLE
Make dpos consensus variables configurable

### ISSUE THREAD

**Issue by manxiaqu** [themis-network/go-themis#5]
Variables of consensus engine and system contract should be configurable for personal needs or test purpose.
consensus configurable variables list:
* producers: Initial list of producers set in genesis block (the producer's info will not be added into contracts, so they have to reg for producers too to be selected as bp after first epoch)
* blockPeriod: Number of seconds between blocks to enforce
* epoch: Number of blocks to propose new producers
Variables of consensus can not be updated once set.

system contract configurable variables list:
* producerSize: Number of producers will be selected as block producers producing block
* proposalPeriod: Period of all proposal will be protected, include system contract upgrade proposal/system config update proposal/vote out producer proposal, after which other producers can propose a new proposal to overwrite old one
* depositForProducer: Least deposit should be payed to be a producer candidates.
* stakeForVote: Least stake should be payed to vote for a proxy/producer
* lockTimeForDeposit: Lock time for deposit after producer unreg, after which producer can withdraw deposit 
* lockTimeForStake: Lock time for stake after user unvote, after which user can withdraw staked
Variables of system contract can be updated by producer's vote after implement of configurable of system contract

**Comment by themis-github** [comment]
Before start a dpos based themis blockchain, you have to special a genesis file or use themis main net genesis config to setup your personal blockchain.
